Allow publishing to Github package registry
bodyshopbidsdotcom/snap-style pull request #6
Opened 2019-11-22 21:05 UTC by wahlg

2019-12-10 19:34 UTC, nickstanish requested changes

2019-12-10 19:34 UTC, nickstanish commented on README.md
> +Update the `Snap::Style::VERSION` and commit it
Just need to mention tagging the release

2019-12-10 20:29 UTC, nickstanish approved these changes

2019-12-16 23:05 UTC, santi-h approved these changes

2019-12-17 15:53 UTC, merged